Return-Path: <speakup+bounces-1109-lists+speakup=lfdr.de@linux-speakup.org>
X-Original-To: lists+speakup@lfdr.de
Delivered-To: lists+speakup@lfdr.de
Received: from befuddled.reisers.ca (befuddled.reisers.ca [206.248.184.127])
	by mail.lfdr.de (Postfix) with ESMTP id B0E0B8B2EBF
	for <lists+speakup@lfdr.de>; Fri, 26 Apr 2024 04:37:37 +0200 (CEST)
Authentication-Results: befuddled.reisers.ca;
	dkim=temperror header.d=ccs.covici.com header.i=@ccs.covici.com header.a=rsa-sha256 header.s=default header.b=b2T0i+T8;
	dkim-atps=neutral
Received: by befuddled.reisers.ca (Postfix, from userid 65534)
	id 2D2A7C81C87; Thu, 25 Apr 2024 22:37:36 -0400 (EDT)
Received: from befuddled.reisers.ca (localhost [127.0.0.1])
	by befuddled.reisers.ca (Postfix) with ESMTP id 0CAF5C8104F
	for <lists+speakup@lfdr.de>; Thu, 25 Apr 2024 22:37:36 -0400 (EDT)
X-Original-To: speakup@linux-speakup.org
Delivered-To: speakup@linux-speakup.org
Received: by befuddled.reisers.ca (Postfix, from userid 65534)
	id A7EEFC8104F; Thu, 25 Apr 2024 22:37:27 -0400 (EDT)
Received: from covici.com (debian-2.covici.com [166.84.7.93])
	by befuddled.reisers.ca (Postfix) with ESMTPS id 87E6FC8103D
	for <speakup@linux-speakup.org>; Thu, 25 Apr 2024 22:37:27 -0400 (EDT)
Received: from ccs.covici.com (ccs.covici.com [70.109.51.194])
	(authenticated bits=0)
	by covici.com (8.15.2/8.15.2/Debian-22) with ESMTPSA id 43Q2bjbG353162
	(version=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384 bits=256 verify=NOT);
	Thu, 25 Apr 2024 22:37:47 -0400
Received: from ccs.covici.com (localhost [127.0.0.1])
	by ccs.covici.com (8.17.1.9/8.17.1.9) with ESMTPS id 43Q2bPll170219
	(version=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384 bits=256 verify=NOT);
	Thu, 25 Apr 2024 22:37:25 -0400
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=ccs.covici.com;
	s=default; t=1714099045;
	bh=/UrZ5DphAY9ApBGbwts3xLfs8pRps1grfaysWsb6gXc=;
	h=Date:From:To:Cc:Subject:In-Reply-To:References:Reply-To;
	b=b2T0i+T8PJTqdreuY9dBNRIx8dChwTjoz0MzXBmaIYUgVhRnFgml2ezqxbVCurnK5
	 KLcFcGJ8CSDaG5vwTz8KyTWWmNN5D38u4QgCo/4/JJ8IIOpyzfU28u2xEFWFP5OR96
	 fp1fsAlPGtvPVOqSirRPYNBnac6Ben9L1urYzQU4=
Received: (from covici@localhost)
	by ccs.covici.com (8.17.1.9/8.17.1/Submit) id 43Q2bPH9170218;
	Thu, 25 Apr 2024 22:37:25 -0400
Date: Thu, 25 Apr 2024 22:37:25 -0400
Message-ID: <m3y19026je.wl-covici@ccs.covici.com>
From: John Covici <covici@ccs.covici.com>
To: Jude DaShiell <jdashiel@panix.com>
Cc: speakup@linux-speakup.org
Subject: Re: speakup and gentoo
In-Reply-To: <10acd4eb-8872-1669-0086-fb591ee6cad4@panix.com>
References: <10acd4eb-8872-1669-0086-fb591ee6cad4@panix.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?ISO-8859-4?Q?Goj=F2?=) APEL-LB/10.8 EasyPG/1.0.0
 Emacs/29.3 (x86_64-pc-linux-gnu) MULE/6.0 (HANACHIRUSATO)
Reply-To: covici@ccs.covici.com
Organization: Covici Computer Systems
X-BeenThere: speakup@linux-speakup.org
Precedence: list
List-Id: "Speakup is a screen review system for Linux."
 <speakup.linux-speakup.org>
List-Unsubscribe: <mailto:speakup+unsubscribe@linux-speakup.org>
List-Post: <mailto:speakup@linux-speakup.org>
List-Help: <mailto:speakup+help@linux-speakup.org>
List-Subscribe: <mailto:speakup+subscribe@linux-speakup.org>
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-Bogosity: Ham, tests=bogofilter, spamicity=0.000000, version=1.2.5

See if you can find a hardware synth to install the stage3 and after
that you could emerge espeakup.

On Thu, 25 Apr 2024 19:48:48 -0400,
Jude DaShiell wrote:
> 
> Does anyone on this list know what command to run in gentoo after booting
> is finished to bring up espeak and have espeak read all of what comes up
> on the screen?  I'm using speakup.synth=soft after the speakup command and
> all it says is speakup.synth=soft.
> I can't catch the boot: prompt so need to start this up after booting is
> finished.  Apparently this is an openrc system though stage3 disks can put
> other process managers like systemd on at user option.
> 
> 
> --
>  Jude <jdashiel at panix dot com>
>  "There are four boxes to be used in defense of liberty:
>  soap, ballot, jury, and ammo.
>  Please use in that order."
>  Ed Howdershelt 1940.
> 

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com

