Return-Path: <speakup+bounces-396-lists+speakup=lfdr.de@linux-speakup.org>
X-Original-To: lists+speakup@lfdr.de
Delivered-To: lists+speakup@lfdr.de
Received: from befuddled.reisers.ca (befuddled.reisers.ca [206.248.184.127])
	by mail.lfdr.de (Postfix) with ESMTP id 4A919502C33
	for <lists+speakup@lfdr.de>; Fri, 15 Apr 2022 16:59:43 +0200 (CEST)
Received: by befuddled.reisers.ca (Postfix, from userid 65534)
	id 7DC98380D45; Fri, 15 Apr 2022 10:59:35 -0400 (EDT)
Received: from befuddled.reisers.ca (localhost [127.0.0.1])
	by befuddled.reisers.ca (Postfix) with ESMTP id 6AD4A380AE8
	for <lists+speakup@lfdr.de>; Fri, 15 Apr 2022 10:59:35 -0400 (EDT)
X-Original-To: speakup@linux-speakup.org
Delivered-To: speakup@linux-speakup.org
Received: by befuddled.reisers.ca (Postfix, from userid 65534)
	id E94D0380BA3; Fri, 15 Apr 2022 10:59:30 -0400 (EDT)
Received: from covici.com (debian-2.covici.com [166.84.7.93])
	by befuddled.reisers.ca (Postfix) with ESMTPS id DA2B3380604
	for <speakup@linux-speakup.org>; Fri, 15 Apr 2022 10:59:30 -0400 (EDT)
Received: from ccs.covici.com (ccs.covici.com [70.109.53.110])
	(authenticated bits=0)
	by covici.com (8.15.2/8.15.2/Debian-22) with ESMTPSA id 23FF01J3479693
	(version=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384 bits=256 verify=NOT);
	Fri, 15 Apr 2022 11:00:02 -0400
Received: from ccs.covici.com (localhost [127.0.0.1])
	by ccs.covici.com (8.17.1/8.15.2) with ESMTPS id 23FExPR1825371
	(version=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384 bits=256 verify=NOT);
	Fri, 15 Apr 2022 10:59:26 -0400
Received: (from covici@localhost)
	by ccs.covici.com (8.17.1/8.15.2/Submit) id 23FExP4n825370;
	Fri, 15 Apr 2022 10:59:25 -0400
Date: Fri, 15 Apr 2022 10:59:25 -0400
Message-ID: <m3sfqeo0j6.wl-covici@ccs.covici.com>
From: John Covici <covici@ccs.covici.com>
To: Jude DaShiell <jdashiel@panix.com>
Cc: speakup@linux-speakup.org
Subject: Re: multiple gentoo speakup install failures
In-Reply-To: <c9b13650-c9da-cf15-68f7-9338fe6831@panix.com>
References: <c9b13650-c9da-cf15-68f7-9338fe6831@panix.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM/1.14.9 (=?ISO-8859-4?Q?Goj=F2?=) APEL/10.8 EasyPG/1.0.0 Emacs/27
 (x86_64-pc-linux-gnu) MULE/6.0 (HANACHIRUSATO)
Reply-To: covici@ccs.covici.com
Organization: Covici Computer Systems
X-BeenThere: speakup@linux-speakup.org
Precedence: list
List-Id: "Speakup is a screen review system for Linux."
 <speakup.linux-speakup.org>
List-Unsubscribe: <mailto:speakup+unsubscribe@linux-speakup.org>
List-Post: <mailto:speakup@linux-speakup.org>
List-Help: <mailto:speakup+help@linux-speakup.org>
List-Subscribe: <mailto:speakup+subscribe@linux-speakup.org>
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-Bogosity: Ham, tests=bogofilter, spamicity=0.000000, version=1.2.5

You might try a hardware synth instead and when you compile the kernel
you can fix it up the way you want.  Also, I like to use ssh to
install such a thing, I am pretty sure you can use some boot parameter
on your net install to do this.

On Fri, 15 Apr 2022 10:02:31 -0400,
Jude DaShiell wrote:
> 
> 
> Things run until they don't any longer.
> When they don't run any longer speakup dies.  The speakup cannot be
> revived when this happens.
> Also the system likely crashes since a poweroff command as root fails to
> turn the system off.
> Many times in order to start the computer I have to use the reset button
> in addition to the power button on an 8 core 14gb ram amd system.
> I tried restricting gentoo to one core with nosmp but that didn't help at
> all either.
> I tried with latest stage3 systemd file and latest gentoo-minimal disk.
> So far as I'm concerned, gentoo at this time is uninstallable on this
> system.
> When speakup dies happens at random points during system installation too.
> I got no idea what's going on and would like to know if I'm unique and
> need a new computer or if this happens to others installing gentoo with
> speakup.  I've tried gentoo and gentoo-nofb kernels too.
> The farthest I got in recent install attempts was the emerge-webrsync step
> which failed because of a bad /etc/portage/make.conf file.
> 
> 

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com

